version: '2'
services:  
  staging-deps:
    image: your-image-name
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27017/inventory
      - DEBUG=servicebus*
    networks:
      - default
    depends_on:
      - redis
      - rabbitmq
      - mongo  
  rabbitmq:
      image: rabbitmq:3.6-management
      ports:
        - 15672:15672
      hostname: rabbitmq
      networks:
        - default  
  redis:
      image: redis
      networks:
        - default  
  mongo:
      image: mongo
      ports:
        - 27017:27017
      networks:
        - default  
  staging:
      image: node:alpine
      volumes:
        - .:/usr/src/service
      working_dir: /usr/src/service
      networks:
        - default
      environment:
        - apiUrl=http://staging-deps:3000
        - RABBITMQ_URL=amqp://rabbitmq:5672
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - MONGO_URL=mongodb://mongo:27017/inventory
        - DEBUG=$DEBUG
      command: npm run test:staging  
  clean:
      extends:
        service: staging
      command: rm -rf node_modules  
  install:
      extends: 
        service: staging
      command: npm run install

